@startuml testtest
actor User
participant Frontend
participant Backend
database Database

group login
activate Frontend
    User -> Frontend : Enter login information
    Frontend -> Backend : Request validation
    activate Backend
    Backend -> Database : Validate login information
    activate Database
        alt validation successful
        Backend <- Database : Validation successful 
        Frontend <- Backend : Move to main page
        else validation failure
        Backend <- Database : Validation failed
        deactivate Database
        Frontend <- Backend : Show error message
        deactivate Backend
        Frontend -> Frontend : Retry login page
        end
end
group Send alert
    User -> Frontend : Press "Varsle"
    Frontend -> Backend : Request page
    activate Backend
    Backend -> Frontend : Opens page
    deactivate Backend
    User -> Frontend : Choose theme
    User -> Frontend : Write inputs
    User -> Frontend : Presses "Confirm"

    Frontend -> Backend : Confirming message
    activate Backend
        alt Confirmed
        Backend -> Database : Save message
        activate Database
        Database -> Backend : Confirm saved
        deactivate Database
        Backend -> Frontend : Display confirmation
        else Denied 
        Backend -> Frontend : Display error message
        deactivate Backend
        end
end


@enduml