@startuml Resident send notification
actor Resident
participant Frontend
participant Backend
database Database
participant ChairmanBackend


group Send alert
activate Frontend
    Resident -> Frontend : Press "Varsle"
    Frontend -> Backend : Request page
    activate Backend
    Backend -> Frontend : Opens page
    deactivate Backend
    Resident -> Frontend : Choose theme
    Resident -> Frontend : Write inputs
    Resident -> Frontend : Presses "Confirm"

    Frontend -> Backend : Confirming message
    activate Backend
        alt Confirmed
        Backend -> Database : Save message
        activate Database
        Database -> ChairmanBackend : Send message
        Database -> Backend : Confirm saved
        deactivate Database
        Backend -> Frontend : Display confirmation
        else Denied 
        Backend -> Frontend : Display error message
        deactivate Backend
        end
end


@enduml