@startuml Resident send notification
actor Resident
participant Frontend
participant API
database Database


group Send alert
activate Frontend
    Resident -> Frontend : Press "Varsle"
    Frontend -> API : Request page
    activate API
    API -> Frontend : Opens page
    deactivate API
    Resident -> Frontend : Choose theme
    Resident -> Frontend : Write inputs
    Resident -> Frontend : Presses "Confirm"

    Frontend -> API : Confirming message
    activate API
        alt Confirmed
        API -> Database : Save message
        activate Database
        Database -> API : Confirm saved
        deactivate Database
        API -> Frontend : Display confirmation
        else Denied 
        API -> Frontend : Display error message
        deactivate API
        end
end


@enduml