@startuml Chairman send notification
actor Chairman
participant Frontend
participant API
database Database

group Send alerts
activate Frontend
    Chairman -> Frontend : Press "Varsle"
    Frontend -> API : Request page
activate API
    API -> Frontend : Open page
deactivate API

    Chairman -> Frontend : Choose receiver
    Chairman -> Frontend : Choose alert-type
    Chairman -> Frontend : Write input
    Frontend -> API : Create alert
activate API
    API -> Database : Save alert
activate Database
    Database -> API : Confirm saved
deactivate Database
    API -> API : Send push alert to user
    API -> API : Send SMS
    API -> API : Send e-mail
    API -> Frontend : Display confirmation
deactivate API
    Chairman -> Frontend : Press "Ok"
    Frontend -> Frontend : Refresh page
end

group Cancel 
    Chairman -> Frontend : Press "Avbryt"
    Frontend -> API : Request cancellation
activate API
    API -> Frontend : Redirect to main page
deactivate API
end


@enduml