@startuml User send notification
actor User
participant Frontend
participant Backend
database Database
participant StyrerBackend


group Send alert
activate Frontend
    User -> Frontend : Press "Varsle"
    Frontend -> Backend : Request page
    activate Backend
    Backend -> Frontend : Opens page
    deactivate Backend
    User -> Frontend : Choose theme
    User -> Frontend : Write inputs
    User -> Frontend : Presses "Confirm"

    Frontend -> Backend : Confirming message
    activate Backend
        alt Confirmed
        Backend -> Database : Save message
        activate Database
        Database -> StyrerBackend : Send message
        Database -> Backend : Confirm saved
        deactivate Database
        Backend -> Frontend : Display confirmation
        else Denied 
        Backend -> Frontend : Display error message
        deactivate Backend
        end
end


@enduml