@startuml testtest
actor User
participant Frontend
participant Backend
database Database

group Log in with token
activate Frontend
    User -> Frontend : Request token
        alt Token found 
        Frontend -> Backend : Validate token
        activate Backend 
        Backend -> Database : Find token
        activate Database 
            alt Token is in database
            Database -> Backend : Return matching user
            Backend -> Frontend : Open main page
            else Token not in database 
            Database ->x Backend : Return error
            deactivate Database 
            Backend -> Frontend : Open loginpage
            deactivate Backend
            end
        else Token not found 
        Frontend -> Frontend : Open loginpage

    end
end 
group Log in without token
    User -> Frontend : Enter login information
    User -> Frontend : Accept to be remembered
    User -> Frontend : Press "Log in"

    Frontend -> Backend : Request validation
    activate Backend
    Backend -> Database : Validate login information
    activate Database
        alt validation successful
        Backend <- Database : Validation successful 
        Backend -> Backend : Create token 
        Backend -> Database : Add token to database
        Database -> Backend : Confirm token added 
        Backend -> User : Add token to user
        Frontend <- Backend : Move to main page
        else validation failure
        Backend x<- Database : Validation failed
        deactivate Database
        Frontend <- Backend : Show error message
        deactivate Backend
        Frontend -> Frontend : Retry login page
        end
end

@enduml