@startwbs Mobile hierarchy 1
* Mobile application 
** Login-page
*** Authenticate user
*** Persistent login 

** Home-page
*** Activity board
**** Pinned post
**** Filter

** Profile-page
*** Delete
*** Preferred contact
*** Edit information
**** Password
**** Email
**** Telephone 


** Notification-page
*** Receive push
*** Notification icon


@endwbs 